using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class ProductDefinition
{
    public string id { get; set; }
    public string gtin { get; set; }
    public string name { get; set; }
    public string type { get; set; }
    public int nutri_score { get; set; }
    public string nutri_label { get; set; }
    public string calories { get; set; }
    public string caloriesColor { get; set; }
    public string sugar { get; set; }
    public string sugarColor { get; set; }
    public string fat { get; set; }
    public string fatColor { get; set; }
    public string protein { get; set; }
    public string proteinColor { get; set; }
    public string fiber { get; set; }
    public string fiberColor { get; set; }
    public string natrium { get; set; }
    public string natriumColor { get; set; }
    public string healthpercentage { get; set; }
    public string healthpercentageColor { get; set; }

}



public class SelectaObjects {

    /// <summary>
    /// Function called at start to initialize the ProductNutris Dict
    /// </summary>
    public static Dictionary<string, ProductDefinition> SetProductNutrisDict()
    {
        Dictionary<string, ProductDefinition> ProductNutris = new Dictionary<string, ProductDefinition>();

        //TODO read this from a file or from the API
        ProductDefinition productDefinition1 = new ProductDefinition();
        productDefinition1.id = "7days_croissantschoko_packung_80_1_0000000000003";
        productDefinition1.name = "7days Croissant Schoko";
        productDefinition1.gtin = "0000000000003";
        productDefinition1.type = "Food";
        productDefinition1.nutri_score = 12;
        productDefinition1.nutri_label = "D";
        productDefinition1.calories = "440.0";
        productDefinition1.caloriesColor = "D";
        productDefinition1.sugar = "19.0";
        productDefinition1.sugarColor = "C";
        productDefinition1.fat = "18.0";
        productDefinition1.fatColor = "E";
        productDefinition1.protein = "7.0";
        productDefinition1.proteinColor = "A";
        productDefinition1.fiber = "3.0";
        productDefinition1.fiberColor = "A";
        productDefinition1.natrium = "0.00";
        productDefinition1.natriumColor = "B";
        productDefinition1.healthpercentage = "0";
        productDefinition1.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition1.id, productDefinition1);

        ProductDefinition productDefinition2 = new ProductDefinition();
        productDefinition2.id = "airwaves_menthoneucalyptus_riegel_14_1_50173167";
        productDefinition2.name = "Airwaves M&E";
        productDefinition2.gtin = "50173167";
        productDefinition2.type = "Food";
        productDefinition2.nutri_score = 1;
        productDefinition2.nutri_label = "B";
        productDefinition2.calories = "142.0";
        productDefinition2.caloriesColor = "B";
        productDefinition2.sugar = "0.0";
        productDefinition2.sugarColor = "B";
        productDefinition2.fat = "0.0";
        productDefinition2.fatColor = "B";
        productDefinition2.protein = "0.0";
        productDefinition2.proteinColor = "C";
        productDefinition2.fiber = "0";
        productDefinition2.fiberColor = "C";
        productDefinition2.natrium = "0.00";
        productDefinition2.natriumColor = "B";
        productDefinition2.healthpercentage = "0.0";
        productDefinition2.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition2.id, productDefinition2);

        ProductDefinition productDefinition3 = new ProductDefinition();
        productDefinition3.id = "balisto_muesli__37g__5000159418546";
        productDefinition3.name = "Balisto Muesli";
        productDefinition3.gtin = "5000159418546";
        productDefinition3.type = "Food";
        productDefinition3.nutri_score = 3;
        productDefinition3.nutri_label = "C";
        productDefinition3.calories = "93.0";
        productDefinition3.caloriesColor = "B";
        productDefinition3.sugar = "8.1";
        productDefinition3.sugarColor = "B";
        productDefinition3.fat = "2.0";
        productDefinition3.fatColor = "B";
        productDefinition3.protein = "1.1";
        productDefinition3.proteinColor = "C";
        productDefinition3.fiber = "0";
        productDefinition3.fiberColor = "C";
        productDefinition3.natrium = "0.05";
        productDefinition3.natriumColor = "B";
        productDefinition3.healthpercentage = "0";
        productDefinition3.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition3.id, productDefinition3);

        ProductDefinition productDefinition4 = new ProductDefinition();
        productDefinition4.id = "berger_zitronetoertli__50__7610404511007";
        productDefinition4.name = "Berger Zitronentörtli";
        productDefinition4.gtin = "7610404511007";
        productDefinition4.type = "Food";
        productDefinition4.nutri_score = 5;
        productDefinition4.nutri_label = "C";
        productDefinition4.calories = "378.0";
        productDefinition4.caloriesColor = "C";
        productDefinition4.sugar = "22.0";
        productDefinition4.sugarColor = "C";
        productDefinition4.fat = "1.7";
        productDefinition4.fatColor = "B";
        productDefinition4.protein = "5.3";
        productDefinition4.proteinColor = "A";
        productDefinition4.fiber = "1.2";
        productDefinition4.fiberColor = "B";
        productDefinition4.natrium = "0.06";
        productDefinition4.natriumColor = "B";
        productDefinition4.healthpercentage = "0";
        productDefinition4.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition4.id, productDefinition4);

        ProductDefinition productDefinition5 = new ProductDefinition();
        productDefinition5.id = "berger_spitzbueb__74__7610404591009";
        productDefinition5.name = "Berger Spitzbueb";
        productDefinition5.gtin = "7610404591009";
        productDefinition5.type = "Food";
        productDefinition5.nutri_score = 17;
        productDefinition5.nutri_label = "D";
        productDefinition5.calories = "401.0";
        productDefinition5.caloriesColor = "D";
        productDefinition5.sugar = "22.5";
        productDefinition5.sugarColor = "C";
        productDefinition5.fat = "12.3";
        productDefinition5.fatColor = "E";
        productDefinition5.protein = "5.2";
        productDefinition5.proteinColor = "A";
        productDefinition5.fiber = "1.7";
        productDefinition5.fiberColor = "B";
        productDefinition5.natrium = "0.20";
        productDefinition5.natriumColor = "C";
        productDefinition5.healthpercentage = "5.75";
        productDefinition5.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition5.id, productDefinition5);

        ProductDefinition productDefinition6 = new ProductDefinition();
        productDefinition6.id = "bifi_roll__50__4251097402635";
        productDefinition6.name = "Bifi Roll";
        productDefinition6.gtin = "4251097402635";
        productDefinition6.type = "Food";
        productDefinition6.nutri_score = 19;
        productDefinition6.nutri_label = "E";
        productDefinition6.calories = "450.0";
        productDefinition6.caloriesColor = "D";
        productDefinition6.sugar = "3.5";
        productDefinition6.sugarColor = "B";
        productDefinition6.fat = "14.0";
        productDefinition6.fatColor = "E";
        productDefinition6.protein = "15.0";
        productDefinition6.proteinColor = "A";
        productDefinition6.fiber = "1.5";
        productDefinition6.fiberColor = "B";
        productDefinition6.natrium = "0.92";
        productDefinition6.natriumColor = "E";
        productDefinition6.healthpercentage = "0";
        productDefinition6.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition6.id, productDefinition6);

        ProductDefinition productDefinition7 = new ProductDefinition();
        productDefinition7.id = "bueno___43__4008400320328";
        productDefinition7.name = "Kinder Bueno";
        productDefinition7.gtin = "4008400320328";
        productDefinition7.type = "Food";
        productDefinition7.nutri_score = 16;
        productDefinition7.nutri_label = "D";
        productDefinition7.calories = "122.0";
        productDefinition7.caloriesColor = "B";
        productDefinition7.sugar = "41.2";
        productDefinition7.sugarColor = "E";
        productDefinition7.fat = "17.3";
        productDefinition7.fatColor = "E";
        productDefinition7.protein = "8.6";
        productDefinition7.proteinColor = "A";
        productDefinition7.fiber = "0.0";
        productDefinition7.fiberColor = "C";
        productDefinition7.natrium = "0.11";
        productDefinition7.natriumColor = "B";
        productDefinition7.healthpercentage = "0";
        productDefinition7.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition7.id, productDefinition7);

        ProductDefinition productDefinition8 = new ProductDefinition();
        productDefinition8.id = "c+swiss_dosenabisicetea__33__9120025930135";
        productDefinition8.name = "C+Swiss Canabis Ice Tea";
        productDefinition8.gtin = "9120025930135";
        productDefinition8.type = "Drink";
        productDefinition8.nutri_score = 7;
        productDefinition8.nutri_label = "D";
        productDefinition8.calories = "31.0";
        productDefinition8.caloriesColor = "C";
        productDefinition8.sugar = "7.4";
        productDefinition8.sugarColor = "D";
        productDefinition8.fat = "0.0";
        productDefinition8.fatColor = "B";
        productDefinition8.protein = "0.0";
        productDefinition8.proteinColor = "C";
        productDefinition8.fiber = "0.0";
        productDefinition8.fiberColor = "C";
        productDefinition8.natrium = "0.01";
        productDefinition8.natriumColor = "B";
        productDefinition8.healthpercentage = "0";
        productDefinition8.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition8.id, productDefinition8);

        ProductDefinition productDefinition9 = new ProductDefinition();
        productDefinition9.id = "caferoyal_classicmacchiato__33__7617014164487";
        productDefinition9.name = "Cafe Royal Classic Macchiato";
        productDefinition9.gtin = "7617014164487";
        productDefinition9.type = "Drink";
        productDefinition9.nutri_score = 2;
        productDefinition9.nutri_label = "B";
        productDefinition9.calories = "73.0";
        productDefinition9.caloriesColor = "B";
        productDefinition9.sugar = "9.7";
        productDefinition9.sugarColor = "C";
        productDefinition9.fat = "1.5";
        productDefinition9.fatColor = "B";
        productDefinition9.protein = "2.8";
        productDefinition9.proteinColor = "B";
        productDefinition9.fiber = "0";
        productDefinition9.fiberColor = "C";
        productDefinition9.natrium = "0.08";
        productDefinition9.natriumColor = "B";
        productDefinition9.healthpercentage = "0.0";
        productDefinition9.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition9.id, productDefinition9);

        ProductDefinition productDefinition10 = new ProductDefinition();
        productDefinition10.id = "caprisun_multivitamin__20__4000177605004";
        productDefinition10.name = "Capri-Sun - Multivitamin";
        productDefinition10.gtin = "4000177605004";
        productDefinition10.type = "Drink";
        productDefinition10.nutri_score = 7;
        productDefinition10.nutri_label = "D";
        productDefinition10.calories = "39.0";
        productDefinition10.caloriesColor = "C";
        productDefinition10.sugar = "9.0";
        productDefinition10.sugarColor = "D";
        productDefinition10.fat = "0.1";
        productDefinition10.fatColor = "B";
        productDefinition10.protein = "0.5";
        productDefinition10.proteinColor = "C";
        productDefinition10.fiber = "0.0";
        productDefinition10.fiberColor = "C";
        productDefinition10.natrium = "0.00";
        productDefinition10.natriumColor = "B";
        productDefinition10.healthpercentage = "12.0";
        productDefinition10.healthpercentageColor = "B";
        ProductNutris.Add(productDefinition10.id, productDefinition10);

        ProductDefinition productDefinition11 = new ProductDefinition();
        productDefinition11.id = "coke_zero_flasche_50__5449000131836";
        productDefinition11.name = "Coca-Cola zero PET";
        productDefinition11.gtin = "5449000131836";
        productDefinition11.type = "Drink";
        productDefinition11.nutri_score = 0;
        productDefinition11.nutri_label = "B";
        productDefinition11.calories = "0.2";
        productDefinition11.caloriesColor = "B";
        productDefinition11.sugar = "0.0";
        productDefinition11.sugarColor = "B";
        productDefinition11.fat = "0.0";
        productDefinition11.fatColor = "B";
        productDefinition11.protein = "0.0";
        productDefinition11.proteinColor = "C";
        productDefinition11.fiber = "0.0";
        productDefinition11.fiberColor = "C";
        productDefinition11.natrium = "0.00";
        productDefinition11.natriumColor = "B";
        productDefinition11.healthpercentage = "0.0";
        productDefinition11.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition11.id, productDefinition11);

        ProductDefinition productDefinition12 = new ProductDefinition();
        productDefinition12.id = "coke___50__54491472";
        productDefinition12.name = "Coca-Cola PET";
        productDefinition12.gtin = "54491472";
        productDefinition12.type = "Drink";
        productDefinition12.nutri_score = 10;
        productDefinition12.nutri_label = "E";
        productDefinition12.calories = "42.0";
        productDefinition12.caloriesColor = "C";
        productDefinition12.sugar = "10.6";
        productDefinition12.sugarColor = "E";
        productDefinition12.fat = "0.0";
        productDefinition12.fatColor = "B";
        productDefinition12.protein = "0.0";
        productDefinition12.proteinColor = "C";
        productDefinition12.fiber = "0.0";
        productDefinition12.fiberColor = "C";
        productDefinition12.natrium = "0.04";
        productDefinition12.natriumColor = "B";
        productDefinition12.healthpercentage = "0.0";
        productDefinition12.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition12.id, productDefinition12);

        ProductDefinition productDefinition13 = new ProductDefinition();
        productDefinition13.id = "comella_schokodrink__33__7613100037253";
        productDefinition13.name = "COMELLA Choco Drink";
        productDefinition13.gtin = "7613100037253";
        productDefinition13.type = "Drink";
        productDefinition13.nutri_score = 0;
        productDefinition13.nutri_label = "B";
        productDefinition13.calories = "66.0";
        productDefinition13.caloriesColor = "B";
        productDefinition13.sugar = "10.0";
        productDefinition13.sugarColor = "C";
        productDefinition13.fat = "0.6";
        productDefinition13.fatColor = "B";
        productDefinition13.protein = "4.5";
        productDefinition13.proteinColor = "B";
        productDefinition13.fiber = "0";
        productDefinition13.fiberColor = "C";
        productDefinition13.natrium = "0.04";
        productDefinition13.natriumColor = "B";
        productDefinition13.healthpercentage = "0";
        productDefinition13.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition13.id, productDefinition13);

        ProductDefinition productDefinition14 = new ProductDefinition();
        productDefinition14.id = "darwida_sandwich____7610032065170";
        productDefinition14.name = "DAR-VIDA Sandwich";
        productDefinition14.gtin = "7610032065170";
        productDefinition14.type = "Food";
        productDefinition14.nutri_score = 8;
        productDefinition14.nutri_label = "C";
        productDefinition14.calories = "483.0";
        productDefinition14.caloriesColor = "D";
        productDefinition14.sugar = "3.0";
        productDefinition14.sugarColor = "B";
        productDefinition14.fat = "6.0";
        productDefinition14.fatColor = "D";
        productDefinition14.protein = "10.0";
        productDefinition14.proteinColor = "A";
        productDefinition14.fiber = "5.0";
        productDefinition14.fiberColor = "A";
        productDefinition14.natrium = "0.67";
        productDefinition14.natriumColor = "E";
        productDefinition14.healthpercentage = "0";
        productDefinition14.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition14.id, productDefinition14);

        ProductDefinition productDefinition15 = new ProductDefinition();
        productDefinition15.id = "evian___50__3068320353500";
        productDefinition15.name = "Evian Natural";
        productDefinition15.gtin = "3068320353500";
        productDefinition15.type = "Drink";
        productDefinition15.nutri_score = -15;
        productDefinition15.nutri_label = "A";
        productDefinition15.calories = "0.0";
        productDefinition15.caloriesColor = "B";
        productDefinition15.sugar = "0.0";
        productDefinition15.sugarColor = "B";
        productDefinition15.fat = "0.0";
        productDefinition15.fatColor = "B";
        productDefinition15.protein = "0.0";
        productDefinition15.proteinColor = "C";
        productDefinition15.fiber = "0.0";
        productDefinition15.fiberColor = "C";
        productDefinition15.natrium = "0.01";
        productDefinition15.natriumColor = "B";
        productDefinition15.healthpercentage = "0.0";
        productDefinition15.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition15.id, productDefinition15);

        ProductDefinition productDefinition16 = new ProductDefinition();
        productDefinition16.id = "fanta___50__40822938";
        productDefinition16.name = "Fanta Orange PET";
        productDefinition16.gtin = "40822938";
        productDefinition16.type = "Drink";
        productDefinition16.nutri_score = 11;
        productDefinition16.nutri_label = "E";
        productDefinition16.calories = "51.0";
        productDefinition16.caloriesColor = "C";
        productDefinition16.sugar = "12.2";
        productDefinition16.sugarColor = "E";
        productDefinition16.fat = "0.0";
        productDefinition16.fatColor = "B";
        productDefinition16.protein = "0.0";
        productDefinition16.proteinColor = "C";
        productDefinition16.fiber = "0.0";
        productDefinition16.fiberColor = "C";
        productDefinition16.natrium = "0.01";
        productDefinition16.natriumColor = "B";
        productDefinition16.healthpercentage = "0.0";
        productDefinition16.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition16.id, productDefinition16);

        ProductDefinition productDefinition17 = new ProductDefinition();
        productDefinition17.id = "fini_galaxymix_packung_100_1_8410525150364";
        productDefinition17.name = "Fini Galaxymix";
        productDefinition17.gtin = "8410525150364";
        productDefinition17.type = "Food";
        productDefinition17.nutri_score = 10;
        productDefinition17.nutri_label = "C";
        productDefinition17.calories = "320.0";
        productDefinition17.caloriesColor = "C";
        productDefinition17.sugar = "54.0";
        productDefinition17.sugarColor = "E";
        productDefinition17.fat = "0.0";
        productDefinition17.fatColor = "B";
        productDefinition17.protein = "5.0";
        productDefinition17.proteinColor = "A";
        productDefinition17.fiber = "0";
        productDefinition17.fiberColor = "C";
        productDefinition17.natrium = "0.04";
        productDefinition17.natriumColor = "B";
        productDefinition17.healthpercentage = "0";
        productDefinition17.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition17.id, productDefinition17);

        ProductDefinition productDefinition18 = new ProductDefinition();
        productDefinition18.id = "fini_jellykisses_packung_80_1_8410525116704";
        productDefinition18.name = "Fini Jellykisses";
        productDefinition18.gtin = "8410525116704";
        productDefinition18.type = "Food";
        productDefinition18.nutri_score = 12;
        productDefinition18.nutri_label = "D";
        productDefinition18.calories = "326.4";
        productDefinition18.caloriesColor = "C";
        productDefinition18.sugar = "58.0";
        productDefinition18.sugarColor = "E";
        productDefinition18.fat = "0.0";
        productDefinition18.fatColor = "B";
        productDefinition18.protein = "4.0";
        productDefinition18.proteinColor = "B";
        productDefinition18.fiber = "0";
        productDefinition18.fiberColor = "C";
        productDefinition18.natrium = "0.04";
        productDefinition18.natriumColor = "B";
        productDefinition18.healthpercentage = "0";
        productDefinition18.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition18.id, productDefinition18);

        ProductDefinition productDefinition19 = new ProductDefinition();
        productDefinition19.id = "fuse_peach__50__5449000236623";
        productDefinition19.name = "Fusetea Peach Hibiscus PET";
        productDefinition19.gtin = "5449000236623";
        productDefinition19.type = "Drink";
        productDefinition19.nutri_score = 4;
        productDefinition19.nutri_label = "C";
        productDefinition19.calories = "19.0";
        productDefinition19.caloriesColor = "B";
        productDefinition19.sugar = "4.5";
        productDefinition19.sugarColor = "C";
        productDefinition19.fat = "0.0";
        productDefinition19.fatColor = "B";
        productDefinition19.protein = "0.0";
        productDefinition19.proteinColor = "C";
        productDefinition19.fiber = "0.0";
        productDefinition19.fiberColor = "C";
        productDefinition19.natrium = "0.01";
        productDefinition19.natriumColor = "B";
        productDefinition19.healthpercentage = "0";
        productDefinition19.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition19.id, productDefinition19);

        ProductDefinition productDefinition20 = new ProductDefinition();
        productDefinition20.id = "fuse_lemon_dose_33__5449000235947";
        productDefinition20.name = "Fusetea Lemon Lemongrass PET";
        productDefinition20.gtin = "5449000235947";
        productDefinition20.type = "Drink";
        productDefinition20.nutri_score = 4;
        productDefinition20.nutri_label = "C";
        productDefinition20.calories = "19.0";
        productDefinition20.caloriesColor = "B";
        productDefinition20.sugar = "4.4";
        productDefinition20.sugarColor = "C";
        productDefinition20.fat = "0.0";
        productDefinition20.fatColor = "B";
        productDefinition20.protein = "0.0";
        productDefinition20.proteinColor = "C";
        productDefinition20.fiber = "0.0";
        productDefinition20.fiberColor = "C";
        productDefinition20.natrium = "0.01";
        productDefinition20.natriumColor = "B";
        productDefinition20.healthpercentage = "0.0";
        productDefinition20.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition20.id, productDefinition20);

        ProductDefinition productDefinition21 = new ProductDefinition();
        productDefinition21.id = "granini_orange__50__4002160092334";
        productDefinition21.name = "Granini Orangejuice PET";
        productDefinition21.gtin = "4002160092334";
        productDefinition21.type = "Drink";
        productDefinition21.nutri_score = 4;
        productDefinition21.nutri_label = "C";
        productDefinition21.calories = "19.0";
        productDefinition21.caloriesColor = "B";
        productDefinition21.sugar = "4.4";
        productDefinition21.sugarColor = "C";
        productDefinition21.fat = "0.0";
        productDefinition21.fatColor = "B";
        productDefinition21.protein = "0.0";
        productDefinition21.proteinColor = "C";
        productDefinition21.fiber = "0.0";
        productDefinition21.fiberColor = "C";
        productDefinition21.natrium = "0.01";
        productDefinition21.natriumColor = "B";
        productDefinition21.healthpercentage = "0";
        productDefinition21.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition21.id, productDefinition21);

        ProductDefinition productDefinition22 = new ProductDefinition();
        productDefinition22.id = "henniez_blau__33__7610235000442";
        productDefinition22.name = "Henniez Blau";
        productDefinition22.gtin = "7610235000442";
        productDefinition22.type = "Drink";
        productDefinition22.nutri_score = -15;
        productDefinition22.nutri_label = "A";
        productDefinition22.calories = "0";
        productDefinition22.caloriesColor = "B";
        productDefinition22.sugar = "0";
        productDefinition22.sugarColor = "B";
        productDefinition22.fat = "0";
        productDefinition22.fatColor = "B";
        productDefinition22.protein = "0";
        productDefinition22.proteinColor = "C";
        productDefinition22.fiber = "0";
        productDefinition22.fiberColor = "C";
        productDefinition22.natrium = "0.00";
        productDefinition22.natriumColor = "B";
        productDefinition22.healthpercentage = "0";
        productDefinition22.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition22.id, productDefinition22);

        ProductDefinition productDefinition23 = new ProductDefinition();
        productDefinition23.id = "jacklinks_beefjerkyorginal__25__4047751730219";
        productDefinition23.name = "Jacklinks Beef Jerky Original";
        productDefinition23.gtin = "4047751730219";
        productDefinition23.type = "Food";
        productDefinition23.nutri_score = 11;
        productDefinition23.nutri_label = "D";
        productDefinition23.calories = "289.9032";
        productDefinition23.caloriesColor = "C";
        productDefinition23.sugar = "14.0";
        productDefinition23.sugarColor = "C";
        productDefinition23.fat = "1.0";
        productDefinition23.fatColor = "B";
        productDefinition23.protein = "46.0";
        productDefinition23.proteinColor = "A";
        productDefinition23.fiber = "0.0";
        productDefinition23.fiberColor = "C";
        productDefinition23.natrium = "1.90";
        productDefinition23.natriumColor = "E";
        productDefinition23.healthpercentage = "0";
        productDefinition23.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition23.id, productDefinition23);

        ProductDefinition productDefinition24 = new ProductDefinition();
        productDefinition24.id = "jlbrichard_gauffrechoko__90__5410495002079";
        productDefinition24.name = "JL Brichard Gauffre Choco";
        productDefinition24.gtin = "5410495002079";
        productDefinition24.type = "Food";
        productDefinition24.nutri_score = 19;
        productDefinition24.nutri_label = "E";
        productDefinition24.calories = "464.0";
        productDefinition24.caloriesColor = "D";
        productDefinition24.sugar = "28.0";
        productDefinition24.sugarColor = "D";
        productDefinition24.fat = "15.2";
        productDefinition24.fatColor = "E";
        productDefinition24.protein = "6.0";
        productDefinition24.proteinColor = "A";
        productDefinition24.fiber = "1.8";
        productDefinition24.fiberColor = "B";
        productDefinition24.natrium = "0.21";
        productDefinition24.natriumColor = "C";
        productDefinition24.healthpercentage = "0.0";
        productDefinition24.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition24.id, productDefinition24);

        ProductDefinition productDefinition25 = new ProductDefinition();
        productDefinition25.id = "jlbrichard_gauffre__90__5410495002000";
        productDefinition25.name = "J-L Brichard Gauffre";
        productDefinition25.gtin = "5410495002000";
        productDefinition25.type = "Food";
        productDefinition25.nutri_score = 21;
        productDefinition25.nutri_label = "E";
        productDefinition25.calories = "447.0";
        productDefinition25.caloriesColor = "D";
        productDefinition25.sugar = "27.1";
        productDefinition25.sugarColor = "D";
        productDefinition25.fat = "11.3";
        productDefinition25.fatColor = "E";
        productDefinition25.protein = "6.0";
        productDefinition25.proteinColor = "A";
        productDefinition25.fiber = "1.5";
        productDefinition25.fiberColor = "B";
        productDefinition25.natrium = "0.43";
        productDefinition25.natriumColor = "C";
        productDefinition25.healthpercentage = "0.0";
        productDefinition25.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition25.id, productDefinition25);

        ProductDefinition productDefinition26 = new ProductDefinition();
        productDefinition26.id = "kagi___50__7610046000259";
        productDefinition26.name = "Kägi Fret";
        productDefinition26.gtin = "7610046000259";
        productDefinition26.type = "Food";
        productDefinition26.nutri_score = 19;
        productDefinition26.nutri_label = "E";
        productDefinition26.calories = "559.0";
        productDefinition26.caloriesColor = "D";
        productDefinition26.sugar = "38.0";
        productDefinition26.sugarColor = "E";
        productDefinition26.fat = "25.0";
        productDefinition26.fatColor = "E";
        productDefinition26.protein = "6.4";
        productDefinition26.proteinColor = "A";
        productDefinition26.fiber = "3.1";
        productDefinition26.fiberColor = "A";
        productDefinition26.natrium = "0.09";
        productDefinition26.natriumColor = "B";
        productDefinition26.healthpercentage = "0";
        productDefinition26.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition26.id, productDefinition26);

        ProductDefinition productDefinition27 = new ProductDefinition();
        productDefinition27.id = "kind_darkchocnutsseasalt__40__0602652176517";
        productDefinition27.name = "Kind Dark Chocolate Nuts & Sea Salt";
        productDefinition27.gtin = "0602652176517";
        productDefinition27.type = "Food";
        productDefinition27.nutri_score = 7;
        productDefinition27.nutri_label = "C";
        productDefinition27.calories = "498.0";
        productDefinition27.caloriesColor = "D";
        productDefinition27.sugar = "13.0";
        productDefinition27.sugarColor = "C";
        productDefinition27.fat = "7.7";
        productDefinition27.fatColor = "E";
        productDefinition27.protein = "14.0";
        productDefinition27.proteinColor = "A";
        productDefinition27.fiber = "18.0";
        productDefinition27.fiberColor = "A";
        productDefinition27.natrium = "0.31";
        productDefinition27.natriumColor = "C";
        productDefinition27.healthpercentage = "60.0";
        productDefinition27.healthpercentageColor = "B";
        ProductNutris.Add(productDefinition27.id, productDefinition27);

        ProductDefinition productDefinition28 = new ProductDefinition();
        productDefinition28.id = "knoppers_riegel____4035800488808";
        productDefinition28.name = "Knoppers Riegel";
        productDefinition28.gtin = "4035800488808";
        productDefinition28.type = "Food";
        productDefinition28.nutri_score = 19;
        productDefinition28.nutri_label = "E";
        productDefinition28.calories = "551.0";
        productDefinition28.caloriesColor = "D";
        productDefinition28.sugar = "35.3";
        productDefinition28.sugarColor = "E";
        productDefinition28.fat = "18.6";
        productDefinition28.fatColor = "E";
        productDefinition28.protein = "8.8";
        productDefinition28.proteinColor = "A";
        productDefinition28.fiber = "0.0";
        productDefinition28.fiberColor = "C";
        productDefinition28.natrium = "0.15";
        productDefinition28.natriumColor = "B";
        productDefinition28.healthpercentage = "0";
        productDefinition28.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition28.id, productDefinition28);

        ProductDefinition productDefinition29 = new ProductDefinition();
        productDefinition29.id = "lorenz_nicnacs__40__4018077798818";
        productDefinition29.name = "Lorenz NicNacs";
        productDefinition29.gtin = "4018077798818";
        productDefinition29.type = "Food";
        productDefinition29.nutri_score = 18;
        productDefinition29.nutri_label = "D";
        productDefinition29.calories = "540.0";
        productDefinition29.caloriesColor = "D";
        productDefinition29.sugar = "7.3";
        productDefinition29.sugarColor = "B";
        productDefinition29.fat = "11.0";
        productDefinition29.fatColor = "E";
        productDefinition29.protein = "15.0";
        productDefinition29.proteinColor = "A";
        productDefinition29.fiber = "4.4";
        productDefinition29.fiberColor = "A";
        productDefinition29.natrium = "0.91";
        productDefinition29.natriumColor = "E";
        productDefinition29.healthpercentage = "0";
        productDefinition29.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition29.id, productDefinition29);

        ProductDefinition productDefinition30 = new ProductDefinition();
        productDefinition30.id = "malburner_partysticks__40__7610200279682";
        productDefinition30.name = "Malbuner Party-Sticks";
        productDefinition30.gtin = "7610200279682";
        productDefinition30.type = "Food";
        productDefinition30.nutri_score = 21;
        productDefinition30.nutri_label = "E";
        productDefinition30.calories = "497.0";
        productDefinition30.caloriesColor = "D";
        productDefinition30.sugar = "1.0";
        productDefinition30.sugarColor = "B";
        productDefinition30.fat = "15.0";
        productDefinition30.fatColor = "E";
        productDefinition30.protein = "35.0";
        productDefinition30.proteinColor = "A";
        productDefinition30.fiber = "0.5";
        productDefinition30.fiberColor = "C";
        productDefinition30.natrium = "1.97";
        productDefinition30.natriumColor = "E";
        productDefinition30.healthpercentage = "0.0";
        productDefinition30.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition30.id, productDefinition30);

        ProductDefinition productDefinition31 = new ProductDefinition();
        productDefinition31.id = "maltesers___100__5000159023061";
        productDefinition31.name = "Maltesers Classic";
        productDefinition31.gtin = "5000159023061";
        productDefinition31.type = "Food";
        productDefinition31.nutri_score = 8;
        productDefinition31.nutri_label = "C";
        productDefinition31.calories = "167.0";
        productDefinition31.caloriesColor = "C";
        productDefinition31.sugar = "17.2";
        productDefinition31.sugarColor = "C";
        productDefinition31.fat = "5.0";
        productDefinition31.fatColor = "C";
        productDefinition31.protein = "2.7";
        productDefinition31.proteinColor = "B";
        productDefinition31.fiber = "0.0";
        productDefinition31.fiberColor = "C";
        productDefinition31.natrium = "0.06";
        productDefinition31.natriumColor = "B";
        productDefinition31.healthpercentage = "0";
        productDefinition31.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition31.id, productDefinition31);

        ProductDefinition productDefinition32 = new ProductDefinition();
        productDefinition32.id = "maltesers_teasers__35__5000159462129";
        productDefinition32.name = "Maltesers Teasers";
        productDefinition32.gtin = "5000159462129";
        productDefinition32.type = "Food";
        productDefinition32.nutri_score = 11;
        productDefinition32.nutri_label = "D";
        productDefinition32.calories = "186.0";
        productDefinition32.caloriesColor = "C";
        productDefinition32.sugar = "18.5";
        productDefinition32.sugarColor = "C";
        productDefinition32.fat = "6.3";
        productDefinition32.fatColor = "D";
        productDefinition32.protein = "2.6";
        productDefinition32.proteinColor = "B";
        productDefinition32.fiber = "0";
        productDefinition32.fiberColor = "C";
        productDefinition32.natrium = "0.05";
        productDefinition32.natriumColor = "B";
        productDefinition32.healthpercentage = "0.0";
        productDefinition32.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition32.id, productDefinition32);

        ProductDefinition productDefinition33 = new ProductDefinition();
        productDefinition33.id = "milka_tender____0000000000008";
        productDefinition33.name = "Milka Tender";
        productDefinition33.gtin = "0000000000008";
        productDefinition33.type = "Food";
        productDefinition33.nutri_score = 20;
        productDefinition33.nutri_label = "E";
        productDefinition33.calories = "425.0";
        productDefinition33.caloriesColor = "D";
        productDefinition33.sugar = "37.5";
        productDefinition33.sugarColor = "E";
        productDefinition33.fat = "12.5";
        productDefinition33.fatColor = "E";
        productDefinition33.protein = "6.0";
        productDefinition33.proteinColor = "A";
        productDefinition33.fiber = "0.0";
        productDefinition33.fiberColor = "C";
        productDefinition33.natrium = "0.00";
        productDefinition33.natriumColor = "B";
        productDefinition33.healthpercentage = "0";
        productDefinition33.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition33.id, productDefinition33);

        ProductDefinition productDefinition34 = new ProductDefinition();
        productDefinition34.id = "mnms_gelb__45__40111445";
        productDefinition34.name = "M&M's Peanut";
        productDefinition34.gtin = "40111445";
        productDefinition34.type = "Food";
        productDefinition34.nutri_score = 9;
        productDefinition34.nutri_label = "C";
        productDefinition34.calories = "230.0";
        productDefinition34.caloriesColor = "C";
        productDefinition34.sugar = "24.1";
        productDefinition34.sugarColor = "D";
        productDefinition34.fat = "4.6";
        productDefinition34.fatColor = "C";
        productDefinition34.protein = "4.4";
        productDefinition34.proteinColor = "B";
        productDefinition34.fiber = "0.0";
        productDefinition34.fiberColor = "C";
        productDefinition34.natrium = "0.02";
        productDefinition34.natriumColor = "B";
        productDefinition34.healthpercentage = "0";
        productDefinition34.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition34.id, productDefinition34);

        ProductDefinition productDefinition35 = new ProductDefinition();
        productDefinition35.id = "mezzomix___50__54490840";
        productDefinition35.name = "Mezzomix PET";
        productDefinition35.gtin = "54490840";
        productDefinition35.type = "Drink";
        productDefinition35.nutri_score = 9;
        productDefinition35.nutri_label = "D";
        productDefinition35.calories = "43.0";
        productDefinition35.caloriesColor = "C";
        productDefinition35.sugar = "10.5";
        productDefinition35.sugarColor = "E";
        productDefinition35.fat = "0.0";
        productDefinition35.fatColor = "B";
        productDefinition35.protein = "0.0";
        productDefinition35.proteinColor = "C";
        productDefinition35.fiber = "0";
        productDefinition35.fiberColor = "C";
        productDefinition35.natrium = "0.00";
        productDefinition35.natriumColor = "B";
        productDefinition35.healthpercentage = "0.0";
        productDefinition35.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition35.id, productDefinition35);

        ProductDefinition productDefinition36 = new ProductDefinition();
        productDefinition36.id = "oreo___66__84100733";
        productDefinition36.name = "Oreo Original 6pcs";
        productDefinition36.gtin = "84100733";
        productDefinition36.type = "Food";
        productDefinition36.nutri_score = 16;
        productDefinition36.nutri_label = "D";
        productDefinition36.calories = "474.0";
        productDefinition36.caloriesColor = "D";
        productDefinition36.sugar = "38.0";
        productDefinition36.sugarColor = "E";
        productDefinition36.fat = "5.2";
        productDefinition36.fatColor = "D";
        productDefinition36.protein = "5.4";
        productDefinition36.proteinColor = "A";
        productDefinition36.fiber = "2.7";
        productDefinition36.fiberColor = "B";
        productDefinition36.natrium = "0.29";
        productDefinition36.natriumColor = "C";
        productDefinition36.healthpercentage = "0";
        productDefinition36.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition36.id, productDefinition36);

        ProductDefinition productDefinition37 = new ProductDefinition();
        productDefinition37.id = "pepsi_max__50__4060800105943";
        productDefinition37.name = "Pepsi Max";
        productDefinition37.gtin = "4060800105943";
        productDefinition37.type = "Drink";
        productDefinition37.nutri_score = 0;
        productDefinition37.nutri_label = "B";
        productDefinition37.calories = "0.0";
        productDefinition37.caloriesColor = "B";
        productDefinition37.sugar = "0.0";
        productDefinition37.sugarColor = "B";
        productDefinition37.fat = "0.0";
        productDefinition37.fatColor = "B";
        productDefinition37.protein = "0.0";
        productDefinition37.proteinColor = "C";
        productDefinition37.fiber = "0.0";
        productDefinition37.fiberColor = "C";
        productDefinition37.natrium = "0.00";
        productDefinition37.natriumColor = "B";
        productDefinition37.healthpercentage = "0";
        productDefinition37.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition37.id, productDefinition37);

        ProductDefinition productDefinition38 = new ProductDefinition();
        productDefinition38.id = "powerbar_proteinplusschoko__55__4029679520028";
        productDefinition38.name = "PowerBar ProteinPlus";
        productDefinition38.gtin = "4029679520028";
        productDefinition38.type = "Food";
        productDefinition38.nutri_score = -3;
        productDefinition38.nutri_label = "A";
        productDefinition38.calories = "187.0";
        productDefinition38.caloriesColor = "C";
        productDefinition38.sugar = "16.0";
        productDefinition38.sugarColor = "C";
        productDefinition38.fat = "2.2";
        productDefinition38.fatColor = "C";
        productDefinition38.protein = "17.0";
        productDefinition38.proteinColor = "A";
        productDefinition38.fiber = "7.4";
        productDefinition38.fiberColor = "A";
        productDefinition38.natrium = "0.05";
        productDefinition38.natriumColor = "B";
        productDefinition38.healthpercentage = "0.0";
        productDefinition38.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition38.id, productDefinition38);

        ProductDefinition productDefinition39 = new ProductDefinition();
        productDefinition39.id = "ragusa___50__76401121";
        productDefinition39.name = "Ragusa";
        productDefinition39.gtin = "76401121";
        productDefinition39.type = "Food";
        productDefinition39.nutri_score = 20;
        productDefinition39.nutri_label = "E";
        productDefinition39.calories = "576.0";
        productDefinition39.caloriesColor = "E";
        productDefinition39.sugar = "49.0";
        productDefinition39.sugarColor = "E";
        productDefinition39.fat = "15.0";
        productDefinition39.fatColor = "E";
        productDefinition39.protein = "7.0";
        productDefinition39.proteinColor = "A";
        productDefinition39.fiber = "3.0";
        productDefinition39.fiberColor = "A";
        productDefinition39.natrium = "0.00";
        productDefinition39.natriumColor = "B";
        productDefinition39.healthpercentage = "0";
        productDefinition39.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition39.id, productDefinition39);

        ProductDefinition productDefinition40 = new ProductDefinition();
        productDefinition40.id = "ramseier_jusdepomme__50__7610057001078";
        productDefinition40.name = "Ramseier Jus de Pomme";
        productDefinition40.gtin = "7610057001078";
        productDefinition40.type = "Drink";
        productDefinition40.nutri_score = 12;
        productDefinition40.nutri_label = "E";
        productDefinition40.calories = "27.0";
        productDefinition40.caloriesColor = "C";
        productDefinition40.sugar = "11.0";
        productDefinition40.sugarColor = "E";
        productDefinition40.fat = "0.0";
        productDefinition40.fatColor = "B";
        productDefinition40.protein = "0.5";
        productDefinition40.proteinColor = "C";
        productDefinition40.fiber = "0";
        productDefinition40.fiberColor = "C";
        productDefinition40.natrium = "0.04";
        productDefinition40.natriumColor = "B";
        productDefinition40.healthpercentage = "0";
        productDefinition40.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition40.id, productDefinition40);

        ProductDefinition productDefinition41 = new ProductDefinition();
        productDefinition41.id = "redbull___33__90162909";
        productDefinition41.name = "Red Bull";
        productDefinition41.gtin = "90162909";
        productDefinition41.type = "Drink";
        productDefinition41.nutri_score = 10;
        productDefinition41.nutri_label = "E";
        productDefinition41.calories = "46.0";
        productDefinition41.caloriesColor = "C";
        productDefinition41.sugar = "11.0";
        productDefinition41.sugarColor = "E";
        productDefinition41.fat = "0.0";
        productDefinition41.fatColor = "B";
        productDefinition41.protein = "0.0";
        productDefinition41.proteinColor = "C";
        productDefinition41.fiber = "0.0";
        productDefinition41.fiberColor = "C";
        productDefinition41.natrium = "0.04";
        productDefinition41.natriumColor = "B";
        productDefinition41.healthpercentage = "0";
        productDefinition41.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition41.id, productDefinition41);

        ProductDefinition productDefinition42 = new ProductDefinition();
        productDefinition42.id = "redbull_light__33__90162800";
        productDefinition42.name = "Red Bull Sugarfree";
        productDefinition42.gtin = "90162800";
        productDefinition42.type = "Drink";
        productDefinition42.nutri_score = 1;
        productDefinition42.nutri_label = "B";
        productDefinition42.calories = "3.0";
        productDefinition42.caloriesColor = "B";
        productDefinition42.sugar = "0.0";
        productDefinition42.sugarColor = "B";
        productDefinition42.fat = "0.0";
        productDefinition42.fatColor = "B";
        productDefinition42.protein = "0.0";
        productDefinition42.proteinColor = "C";
        productDefinition42.fiber = "0.0";
        productDefinition42.fiberColor = "C";
        productDefinition42.natrium = "0.04";
        productDefinition42.natriumColor = "B";
        productDefinition42.healthpercentage = "0.0";
        productDefinition42.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition42.id, productDefinition42);

        ProductDefinition productDefinition43 = new ProductDefinition();
        productDefinition43.id = "rivella_rot__50__7610097111072";
        productDefinition43.name = "Rivella Rot";
        productDefinition43.gtin = "7610097111072";
        productDefinition43.type = "Drink";
        productDefinition43.nutri_score = 8;
        productDefinition43.nutri_label = "D";
        productDefinition43.calories = "37.0";
        productDefinition43.caloriesColor = "C";
        productDefinition43.sugar = "9.0";
        productDefinition43.sugarColor = "D";
        productDefinition43.fat = "0.0";
        productDefinition43.fatColor = "B";
        productDefinition43.protein = "0.0";
        productDefinition43.proteinColor = "C";
        productDefinition43.fiber = "0.0";
        productDefinition43.fiberColor = "C";
        productDefinition43.natrium = "0.01";
        productDefinition43.natriumColor = "B";
        productDefinition43.healthpercentage = "0.0";
        productDefinition43.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition43.id, productDefinition43);

        ProductDefinition productDefinition44 = new ProductDefinition();
        productDefinition44.id = "schweppes_citrus__50__7610238230617";
        productDefinition44.name = "Schweppes Citrus";
        productDefinition44.gtin = "7610238230617";
        productDefinition44.type = "Drink";
        productDefinition44.nutri_score = 8;
        productDefinition44.nutri_label = "D";
        productDefinition44.calories = "35.0";
        productDefinition44.caloriesColor = "C";
        productDefinition44.sugar = "8.5";
        productDefinition44.sugarColor = "D";
        productDefinition44.fat = "0.0";
        productDefinition44.fatColor = "B";
        productDefinition44.protein = "0.0";
        productDefinition44.proteinColor = "C";
        productDefinition44.fiber = "0.0";
        productDefinition44.fiberColor = "C";
        productDefinition44.natrium = "0.00";
        productDefinition44.natriumColor = "B";
        productDefinition44.healthpercentage = "0";
        productDefinition44.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition44.id, productDefinition44);

        ProductDefinition productDefinition45 = new ProductDefinition();
        productDefinition45.id = "stimorol_wildcherry_riegel_14_1_57060330";
        productDefinition45.name = "Stimorol Wildcherry";
        productDefinition45.gtin = "57060330";
        productDefinition45.type = "Food";
        productDefinition45.nutri_score = 2;
        productDefinition45.nutri_label = "B";
        productDefinition45.calories = "182.0";
        productDefinition45.caloriesColor = "C";
        productDefinition45.sugar = "0.1";
        productDefinition45.sugarColor = "B";
        productDefinition45.fat = "0.4";
        productDefinition45.fatColor = "B";
        productDefinition45.protein = "0.4";
        productDefinition45.proteinColor = "C";
        productDefinition45.fiber = "0";
        productDefinition45.fiberColor = "C";
        productDefinition45.natrium = "0.01";
        productDefinition45.natriumColor = "B";
        productDefinition45.healthpercentage = "0";
        productDefinition45.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition45.id, productDefinition45);

        ProductDefinition productDefinition46 = new ProductDefinition();
        productDefinition46.id = "skittles_sour_riegel_51_1_0000000000004";
        productDefinition46.name = "Skittles Sour";
        productDefinition46.gtin = "0000000000004";
        productDefinition46.type = "Food";
        productDefinition46.nutri_score = 16;
        productDefinition46.nutri_label = "D";
        productDefinition46.calories = "398.0";
        productDefinition46.caloriesColor = "C";
        productDefinition46.sugar = "87.4";
        productDefinition46.sugarColor = "E";
        productDefinition46.fat = "2.4";
        productDefinition46.fatColor = "C";
        productDefinition46.protein = "0.0";
        productDefinition46.proteinColor = "C";
        productDefinition46.fiber = "0.0";
        productDefinition46.fiberColor = "C";
        productDefinition46.natrium = "0.00";
        productDefinition46.natriumColor = "B";
        productDefinition46.healthpercentage = "0";
        productDefinition46.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition46.id, productDefinition46);

        ProductDefinition productDefinition47 = new ProductDefinition();
        productDefinition47.id = "snickers___50__5000159461122";
        productDefinition47.name = "Snickers";
        productDefinition47.gtin = "5000159461122";
        productDefinition47.type = "Food";
        productDefinition47.nutri_score = 10;
        productDefinition47.nutri_label = "C";
        productDefinition47.calories = "241.0";
        productDefinition47.caloriesColor = "C";
        productDefinition47.sugar = "26.0";
        productDefinition47.sugarColor = "D";
        productDefinition47.fat = "4.0";
        productDefinition47.fatColor = "C";
        productDefinition47.protein = "4.3";
        productDefinition47.proteinColor = "B";
        productDefinition47.fiber = "0.0";
        productDefinition47.fiberColor = "C";
        productDefinition47.natrium = "0.12";
        productDefinition47.natriumColor = "B";
        productDefinition47.healthpercentage = "0";
        productDefinition47.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition47.id, productDefinition47);

        ProductDefinition productDefinition48 = new ProductDefinition();
        productDefinition48.id = "stimorol_spearmint_riegel_14_1_0000000000005";
        productDefinition48.name = "Stimorol Spearmint";
        productDefinition48.gtin = "0000000000005";
        productDefinition48.type = "Food";
        productDefinition48.nutri_score = 1;
        productDefinition48.nutri_label = "B";
        productDefinition48.calories = "160.0";
        productDefinition48.caloriesColor = "B";
        productDefinition48.sugar = "0.1";
        productDefinition48.sugarColor = "B";
        productDefinition48.fat = "0.3";
        productDefinition48.fatColor = "B";
        productDefinition48.protein = "0.4";
        productDefinition48.proteinColor = "C";
        productDefinition48.fiber = "0.0";
        productDefinition48.fiberColor = "C";
        productDefinition48.natrium = "0.00";
        productDefinition48.natriumColor = "B";
        productDefinition48.healthpercentage = "0";
        productDefinition48.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition48.id, productDefinition48);

        ProductDefinition productDefinition50 = new ProductDefinition();
        productDefinition50.id = "toffifee___33__4014400924275";
        productDefinition50.name = "Storck Toffifee";
        productDefinition50.gtin = "4014400924275";
        productDefinition50.type = "Food";
        productDefinition50.nutri_score = 24;
        productDefinition50.nutri_label = "E";
        productDefinition50.calories = "522.0";
        productDefinition50.caloriesColor = "D";
        productDefinition50.sugar = "48.9";
        productDefinition50.sugarColor = "E";
        productDefinition50.fat = "12.7";
        productDefinition50.fatColor = "E";
        productDefinition50.protein = "6.0";
        productDefinition50.proteinColor = "A";
        productDefinition50.fiber = "0";
        productDefinition50.fiberColor = "C";
        productDefinition50.natrium = "0.10";
        productDefinition50.natriumColor = "B";
        productDefinition50.healthpercentage = "0.0";
        productDefinition50.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition50.id, productDefinition50);

        ProductDefinition productDefinition51 = new ProductDefinition();
        productDefinition51.id = "torino___46__76415272";
        productDefinition51.name = "Torino Milk";
        productDefinition51.gtin = "76415272";
        productDefinition51.type = "Food";
        productDefinition51.nutri_score = 21;
        productDefinition51.nutri_label = "E";
        productDefinition51.calories = "571.0";
        productDefinition51.caloriesColor = "E";
        productDefinition51.sugar = "47.0";
        productDefinition51.sugarColor = "E";
        productDefinition51.fat = "20.0";
        productDefinition51.fatColor = "E";
        productDefinition51.protein = "8.0";
        productDefinition51.proteinColor = "A";
        productDefinition51.fiber = "2.0";
        productDefinition51.fiberColor = "B";
        productDefinition51.natrium = "0.00";
        productDefinition51.natriumColor = "B";
        productDefinition51.healthpercentage = "0";
        productDefinition51.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition51.id, productDefinition51);

        ProductDefinition productDefinition52 = new ProductDefinition();
        productDefinition52.id = "twix___50__5000159459228";
        productDefinition52.name = "Twix";
        productDefinition52.gtin = "5000159459228";
        productDefinition52.type = "Food";
        productDefinition52.nutri_score = 6;
        productDefinition52.nutri_label = "C";
        productDefinition52.calories = "124.0";
        productDefinition52.caloriesColor = "B";
        productDefinition52.sugar = "12.2";
        productDefinition52.sugarColor = "C";
        productDefinition52.fat = "3.5";
        productDefinition52.fatColor = "C";
        productDefinition52.protein = "1.1";
        productDefinition52.proteinColor = "C";
        productDefinition52.fiber = "0.0";
        productDefinition52.fiberColor = "C";
        productDefinition52.natrium = "0.04";
        productDefinition52.natriumColor = "B";
        productDefinition52.healthpercentage = "0.0";
        productDefinition52.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition52.id, productDefinition52);

        ProductDefinition productDefinition53 = new ProductDefinition();
        productDefinition53.id = "valser_vivabirne__50__7610335001530";
        productDefinition53.name = "Valser Viva Pear & Melissa PET";
        productDefinition53.gtin = "7610335001530";
        productDefinition53.type = "Drink";
        productDefinition53.nutri_score = 4;
        productDefinition53.nutri_label = "C";
        productDefinition53.calories = "18.0";
        productDefinition53.caloriesColor = "B";
        productDefinition53.sugar = "4.2";
        productDefinition53.sugarColor = "C";
        productDefinition53.fat = "0.0";
        productDefinition53.fatColor = "B";
        productDefinition53.protein = "0.0";
        productDefinition53.proteinColor = "C";
        productDefinition53.fiber = "0.0";
        productDefinition53.fiberColor = "C";
        productDefinition53.natrium = "0.00";
        productDefinition53.natriumColor = "B";
        productDefinition53.healthpercentage = "0.0";
        productDefinition53.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition53.id, productDefinition53);

        ProductDefinition productDefinition54 = new ProductDefinition();
        productDefinition54.id = "valser_still__50__7610335002575";
        productDefinition54.name = "Valser Still PET";
        productDefinition54.gtin = "7610335002575";
        productDefinition54.type = "Drink";
        productDefinition54.nutri_score = -15;
        productDefinition54.nutri_label = "A";
        productDefinition54.calories = "0.0";
        productDefinition54.caloriesColor = "B";
        productDefinition54.sugar = "0.0";
        productDefinition54.sugarColor = "B";
        productDefinition54.fat = "0.0";
        productDefinition54.fatColor = "B";
        productDefinition54.protein = "0.0";
        productDefinition54.proteinColor = "C";
        productDefinition54.fiber = "0.0";
        productDefinition54.fiberColor = "C";
        productDefinition54.natrium = "0.00";
        productDefinition54.natriumColor = "B";
        productDefinition54.healthpercentage = "0.0";
        productDefinition54.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition54.id, productDefinition54);

        ProductDefinition productDefinition55 = new ProductDefinition();
        productDefinition55.id = "valser_classic__50__76404160";
        productDefinition55.name = "Valser Sparkling PET";
        productDefinition55.gtin = "76404160";
        productDefinition55.type = "Drink";
        productDefinition55.nutri_score = -15;
        productDefinition55.nutri_label = "A";
        productDefinition55.calories = "0.0";
        productDefinition55.caloriesColor = "B";
        productDefinition55.sugar = "0.0";
        productDefinition55.sugarColor = "B";
        productDefinition55.fat = "0.0";
        productDefinition55.fatColor = "B";
        productDefinition55.protein = "0.0";
        productDefinition55.proteinColor = "C";
        productDefinition55.fiber = "0.0";
        productDefinition55.fiberColor = "C";
        productDefinition55.natrium = "0.00";
        productDefinition55.natriumColor = "B";
        productDefinition55.healthpercentage = "0.0";
        productDefinition55.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition55.id, productDefinition55);

        ProductDefinition productDefinition56 = new ProductDefinition();
        productDefinition56.id = "vitaminwell_reload__50__7350042716388";
        productDefinition56.name = "Vitamin Well Reload";
        productDefinition56.gtin = "7350042716388";
        productDefinition56.type = "Drink";
        productDefinition56.nutri_score = 4;
        productDefinition56.nutri_label = "C";
        productDefinition56.calories = "17.0";
        productDefinition56.caloriesColor = "B";
        productDefinition56.sugar = "4.2";
        productDefinition56.sugarColor = "C";
        productDefinition56.fat = "0.0";
        productDefinition56.fatColor = "B";
        productDefinition56.protein = "0.0";
        productDefinition56.proteinColor = "C";
        productDefinition56.fiber = "0.0";
        productDefinition56.fiberColor = "C";
        productDefinition56.natrium = "0.01";
        productDefinition56.natriumColor = "B";
        productDefinition56.healthpercentage = "0.0";
        productDefinition56.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition56.id, productDefinition56);

        ProductDefinition productDefinition57 = new ProductDefinition();
        productDefinition57.id = "volvic_teeminze__50__3057640335648";
        productDefinition57.name = "Volvic Thé - Grüntee Minze";
        productDefinition57.gtin = "3057640335648";
        productDefinition57.type = "Drink";
        productDefinition57.nutri_score = 5;
        productDefinition57.nutri_label = "C";
        productDefinition57.calories = "21.0";
        productDefinition57.caloriesColor = "B";
        productDefinition57.sugar = "4.9";
        productDefinition57.sugarColor = "C";
        productDefinition57.fat = "0.0";
        productDefinition57.fatColor = "B";
        productDefinition57.protein = "0.5";
        productDefinition57.proteinColor = "C";
        productDefinition57.fiber = "0.0";
        productDefinition57.fiberColor = "C";
        productDefinition57.natrium = "0.00";
        productDefinition57.natriumColor = "B";
        productDefinition57.healthpercentage = "0.0";
        productDefinition57.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition57.id, productDefinition57);

        ProductDefinition productDefinition58 = new ProductDefinition();
        productDefinition58.id = "volvic_pinapple__50__305764335648";
        productDefinition58.name = "Volvic Juicy Pinapple";
        productDefinition58.gtin = "305764335648";
        productDefinition58.type = "Drink";
        productDefinition58.nutri_score = 5;
        productDefinition58.nutri_label = "C";
        productDefinition58.calories = "21.0";
        productDefinition58.caloriesColor = "B";
        productDefinition58.sugar = "4.9";
        productDefinition58.sugarColor = "C";
        productDefinition58.fat = "0.0";
        productDefinition58.fatColor = "B";
        productDefinition58.protein = "0.5";
        productDefinition58.proteinColor = "C";
        productDefinition58.fiber = "0.0";
        productDefinition58.fiberColor = "C";
        productDefinition58.natrium = "0.00";
        productDefinition58.natriumColor = "B";
        productDefinition58.healthpercentage = "0";
        productDefinition58.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition58.id, productDefinition58);

        ProductDefinition productDefinition59 = new ProductDefinition();
        productDefinition59.id = "zweifel_graneochilli__100__7610095184009";
        productDefinition59.name = "Zweifel Graneo Mild Chilli";
        productDefinition59.gtin = "7610095184009";
        productDefinition59.type = "Food";
        productDefinition59.nutri_score = 8;
        productDefinition59.nutri_label = "C";
        productDefinition59.calories = "471.0";
        productDefinition59.caloriesColor = "D";
        productDefinition59.sugar = "7.0";
        productDefinition59.sugarColor = "B";
        productDefinition59.fat = "1.5";
        productDefinition59.fatColor = "B";
        productDefinition59.protein = "8.0";
        productDefinition59.proteinColor = "A";
        productDefinition59.fiber = "5.0";
        productDefinition59.fiberColor = "A";
        productDefinition59.natrium = "0.94";
        productDefinition59.natriumColor = "E";
        productDefinition59.healthpercentage = "0.0";
        productDefinition59.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition59.id, productDefinition59);

        ProductDefinition productDefinition60 = new ProductDefinition();
        productDefinition60.id = "zweifel_paprika__90__7610095013002";
        productDefinition60.name = "Zweifel Original Chips Paprika";
        productDefinition60.gtin = "7610095013002";
        productDefinition60.type = "Food";
        productDefinition60.nutri_score = 5;
        productDefinition60.nutri_label = "C";
        productDefinition60.calories = "544.0";
        productDefinition60.caloriesColor = "D";
        productDefinition60.sugar = "5.0";
        productDefinition60.sugarColor = "B";
        productDefinition60.fat = "2.0";
        productDefinition60.fatColor = "B";
        productDefinition60.protein = "6.0";
        productDefinition60.proteinColor = "A";
        productDefinition60.fiber = "5.0";
        productDefinition60.fiberColor = "A";
        productDefinition60.natrium = "0.47";
        productDefinition60.natriumColor = "D";
        productDefinition60.healthpercentage = "0";
        productDefinition60.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition60.id, productDefinition60);



        ProductDefinition productDefinition992 = new ProductDefinition();
        productDefinition992.id = "tiki_himbeer_brause__50__00000000009342";
        productDefinition992.name = "Tiki Himbeer Brause PET";
        productDefinition992.gtin = "00000000009342";
        productDefinition992.type = "Drink";
        productDefinition992.nutri_score = 16;
        productDefinition992.nutri_label = "D";
        productDefinition992.calories = "30.0";
        productDefinition992.caloriesColor = "D";
        productDefinition992.sugar = "12.2";
        productDefinition992.sugarColor = "E";
        productDefinition992.fat = "0.0";
        productDefinition992.fatColor = "B";
        productDefinition992.protein = "0.0";
        productDefinition992.proteinColor = "C";
        productDefinition992.fiber = "0.0";
        productDefinition992.fiberColor = "C";
        productDefinition992.natrium = "0.0";
        productDefinition992.natriumColor = "B";
        productDefinition992.healthpercentage = "0.0";
        productDefinition992.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition992.id, productDefinition992);

        ProductDefinition productDefinition993 = new ProductDefinition();
        productDefinition993.id = "fuse_lemon__50__5449000235947";
        productDefinition993.name = "Fusetea Lemon Lemongrass PET";
        productDefinition993.gtin = "5449000235947";
        productDefinition993.type = "Drink";
        productDefinition993.nutri_score = 4;
        productDefinition993.nutri_label = "C";
        productDefinition993.calories = "19.0";
        productDefinition993.caloriesColor = "B";
        productDefinition993.sugar = "4.4";
        productDefinition993.sugarColor = "C";
        productDefinition993.fat = "0.0";
        productDefinition993.fatColor = "B";
        productDefinition993.protein = "0.0";
        productDefinition993.proteinColor = "C";
        productDefinition993.fiber = "0.0";
        productDefinition993.fiberColor = "C";
        productDefinition993.natrium = "0.01";
        productDefinition993.natriumColor = "B";
        productDefinition993.healthpercentage = "0.0";
        productDefinition993.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition993.id, productDefinition993);

        ProductDefinition productDefinition994 = new ProductDefinition();
        productDefinition994.name = "Henniez Rot";
        productDefinition994.gtin = "7610235000442";
        productDefinition994.type = "Drink";
        productDefinition994.nutri_score = -15;
        productDefinition994.nutri_label = "A";
        productDefinition994.calories = "0";
        productDefinition994.caloriesColor = "B";
        productDefinition994.sugar = "0";
        productDefinition994.sugarColor = "B";
        productDefinition994.fat = "0";
        productDefinition994.fatColor = "B";
        productDefinition994.protein = "0";
        productDefinition994.proteinColor = "C";
        productDefinition994.fiber = "0";
        productDefinition994.fiberColor = "C";
        productDefinition994.natrium = "0";
        productDefinition994.natriumColor = "B";
        productDefinition994.healthpercentage = "0";
        productDefinition994.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition994.id, productDefinition994);

        ProductDefinition productDefinition995 = new ProductDefinition();
        productDefinition995.id = "henniez_gruen__33__7610235000442";
        productDefinition995.name = "Henniez Grün";
        productDefinition995.gtin = "7610235000442";
        productDefinition995.type = "Drink";
        productDefinition995.nutri_score = -15;
        productDefinition995.nutri_label = "A";
        productDefinition995.calories = "0";
        productDefinition995.caloriesColor = "B";
        productDefinition995.sugar = "0";
        productDefinition995.sugarColor = "B";
        productDefinition995.fat = "0";
        productDefinition995.fatColor = "B";
        productDefinition995.protein = "0";
        productDefinition995.proteinColor = "C";
        productDefinition995.fiber = "0";
        productDefinition995.fiberColor = "C";
        productDefinition995.natrium = "0";
        productDefinition995.natriumColor = "B";
        productDefinition995.healthpercentage = "0";
        productDefinition995.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition995.id, productDefinition995);

        ProductDefinition productDefinition996 = new ProductDefinition();
        productDefinition996.id = "coke__dose_33__54491472";
        productDefinition996.name = "Coca-Cola Dose";
        productDefinition996.gtin = "54491472";
        productDefinition996.type = "Drink";
        productDefinition996.nutri_score = 10;
        productDefinition996.nutri_label = "E";
        productDefinition996.calories = "42.0";
        productDefinition996.caloriesColor = "C";
        productDefinition996.sugar = "10.6";
        productDefinition996.sugarColor = "E";
        productDefinition996.fat = "0.0";
        productDefinition996.fatColor = "B";
        productDefinition996.protein = "0.0";
        productDefinition996.proteinColor = "C";
        productDefinition996.fiber = "0.0";
        productDefinition996.fiberColor = "C";
        productDefinition996.natrium = "0.045";
        productDefinition996.natriumColor = "B";
        productDefinition996.healthpercentage = "0.0";
        productDefinition996.healthpercentageColor = "C";
        ProductNutris.Add(productDefinition996.id, productDefinition996);

        ProductDefinition productDefinition997 = new ProductDefinition();
        productDefinition997.id = "milka_tender____";
        productDefinition997.name = "Milka Tender Milchriegel";
        productDefinition997.gtin = "0000000000008";
        productDefinition997.type = "Food";
        productDefinition997.nutri_score = 20;
        productDefinition997.nutri_label = "E";
        productDefinition997.calories = "425";
        productDefinition997.caloriesColor = "D";
        productDefinition997.sugar = "37.5";
        productDefinition997.sugarColor = "E";
        productDefinition997.fat = "12.5";
        productDefinition997.fatColor = "E";
        productDefinition997.protein = "6";
        productDefinition997.proteinColor = "A";
        productDefinition997.fiber = "0";
        productDefinition997.fiberColor = "C";
        productDefinition996.natrium = "-";
        productDefinition996.natriumColor = "None";
        productDefinition996.healthpercentage = "-";
        productDefinition996.healthpercentageColor = "None";
        ProductNutris.Add(productDefinition997.id, productDefinition997);

        ProductDefinition productDefinition998 = new ProductDefinition();
        productDefinition998.id = "snackattack_0000000012";
        productDefinition998.name = "Milka Snack Attack";
        productDefinition998.gtin = "0000000012";
        productDefinition998.type = "Food";
        productDefinition998.nutri_score = 23;
        productDefinition998.nutri_label = "E";
        productDefinition998.calories = "548.0";
        productDefinition998.caloriesColor = "D";
        productDefinition998.sugar = "49";
        productDefinition998.sugarColor = "E";
        productDefinition998.fat = "19.0";
        productDefinition998.fatColor = "E";
        productDefinition998.protein = "5.6";
        productDefinition998.proteinColor = "A";
        productDefinition998.fiber = "1.6";
        productDefinition998.fiberColor = "B";
        productDefinition996.natrium = "-";
        productDefinition996.natriumColor = "None";
        productDefinition996.healthpercentage = "-";
        productDefinition996.healthpercentageColor = "None";
        ProductNutris.Add(productDefinition998.id, productDefinition998);


        ProductDefinition productDefinition999 = new ProductDefinition();
        productDefinition999.id = "None";
        productDefinition999.type = "None";
        ProductNutris.Add(productDefinition999.id, productDefinition999);

        return ProductNutris;
    }

    public static Dictionary<string, string> SetInitialBoxValues(bool newLayout)
    {
        //Todo read this from a file
        Dictionary<string, string> InitialBoxValues = new Dictionary<string, string>();
        if (newLayout)
        {
            InitialBoxValues.Add("10", "zweifel_paprika__90__7610095013002");
            InitialBoxValues.Add("11", "zweifel_paprika__90__7610095013002");
            InitialBoxValues.Add("12", "zweifel_graneochilli__100__7610095184009");
            InitialBoxValues.Add("13", "snackattack_0000000012");
            InitialBoxValues.Add("14", "jlbrichard_gauffre__90__5410495002000");
            InitialBoxValues.Add("20", "fini_galaxymix_packung_100_1_8410525150364");
            InitialBoxValues.Add("21", "jacklinks_beefjerkyorginal__25__4047751730219");
            InitialBoxValues.Add("22", "berger_spitzbueb__74__7610404591009");
            InitialBoxValues.Add("23", "maltesers___100__5000159023061");
            InitialBoxValues.Add("24", "mnms_gelb__45__40111445");
            InitialBoxValues.Add("30", "bueno___43__4008400320328");
            InitialBoxValues.Add("31", "twix___50__5000159459228");
            InitialBoxValues.Add("32", "fini_jellykisses_packung_80_1_8410525116704");
            InitialBoxValues.Add("33", "knoppers_riegel____4035800488808");
            InitialBoxValues.Add("34", "malburner_partysticks__40__7610200279682");
            InitialBoxValues.Add("35", "kagi___50__7610046000259");
            InitialBoxValues.Add("36", "None");
            InitialBoxValues.Add("37", "None");
            InitialBoxValues.Add("38", "None");
            InitialBoxValues.Add("39", "None");
            InitialBoxValues.Add("40", "c+swiss_dosenabisicetea__33__9120025930135");
            InitialBoxValues.Add("41", "c+swiss_dosenabisicetea__33__9120025930135");
            InitialBoxValues.Add("42", "coke__dose_33__54491472");
            InitialBoxValues.Add("43", "henniez_rot__33__7610235000442");
            InitialBoxValues.Add("44", "evian___50__3068320353500");
            InitialBoxValues.Add("45", "caferoyal_classicmacchiato__33__7617014164487");
            InitialBoxValues.Add("46", "comella_schokodrink__33__7613100037253");
            InitialBoxValues.Add("47", "bifi_roll__50__4251097402635");
            InitialBoxValues.Add("48", "caprisun_multivitamin__20__4000177605004");
            InitialBoxValues.Add("49", "caprisun_multivitamin__20__4000177605004");
            InitialBoxValues.Add("50", "redbull___33__90162909");
            InitialBoxValues.Add("51", "redbull___33__90162909");
            InitialBoxValues.Add("52", "redbull___33__90162909");
            InitialBoxValues.Add("53", "redbull_light__33__90162800");
            InitialBoxValues.Add("54", "redbull___33__90162909");
            InitialBoxValues.Add("55", "fuse_lemon_dose_33__5449000235947");
            InitialBoxValues.Add("56", "valser_classic__50__76404160");
            InitialBoxValues.Add("57", "valser_classic__50__76404160");
            InitialBoxValues.Add("58", "valser_still__50__7610335002575");
            InitialBoxValues.Add("59", "valser_still__50__7610335002575");
            InitialBoxValues.Add("60", "coke___50__54491472");
            InitialBoxValues.Add("61", "coke___50__54491472");
            InitialBoxValues.Add("62", "coke_zero_flasche_50__5449000131836");
            InitialBoxValues.Add("63", "fanta___50__40822938");
            InitialBoxValues.Add("64", "fuse_peach__50__5449000236623");
            InitialBoxValues.Add("65", "fuse_peach__50__5449000236623");
            InitialBoxValues.Add("66", "fuse_lemon__50__5449000235947");
            InitialBoxValues.Add("67", "ramseier_jusdepomme__50__7610057001078");
            InitialBoxValues.Add("68", "vitaminwell_reload__50__7350042716388");
            InitialBoxValues.Add("69", "valser_still__50__7610335002575");
        }
        else
        {
            InitialBoxValues.Add("10", "zweifel_paprika__90__7610095013002");
            InitialBoxValues.Add("11", "zweifel_graneochilli__100__7610095184009");
            InitialBoxValues.Add("12", "stimorol_wildcherry_riegel_14_1_57060330");
            InitialBoxValues.Add("13", "knoppers_riegel____4035800488808");
            InitialBoxValues.Add("14", "jlbrichard_gauffrechoko__90__5410495002079");
            InitialBoxValues.Add("15", "stimorol_spearmint_riegel_14_1_0000000000005");
            InitialBoxValues.Add("16", "airwaves_menthoneucalyptus_riegel_14_1_50173167");
            InitialBoxValues.Add("17", "skittles_sour_riegel_51_1_0000000000004");
            InitialBoxValues.Add("20", "fini_galaxymix_packung_100_1_8410525150364");
            InitialBoxValues.Add("21", "jacklinks_beefjerkyorginal__25__4047751730219");
            InitialBoxValues.Add("22", "berger_spitzbueb__74__7610404591009");
            InitialBoxValues.Add("23", "maltesers___100__5000159023061");
            InitialBoxValues.Add("24", "mnms_gelb__45__40111445");
            InitialBoxValues.Add("30", "powerbar_proteinplusschoko__55__4029679520028");
            InitialBoxValues.Add("31", "kagi___50__7610046000259");
            InitialBoxValues.Add("32", "fini_jellykisses_packung_80_1_8410525116704");
            InitialBoxValues.Add("33", "knoppers_riegel____4035800488808");
            InitialBoxValues.Add("34", "lorenz_nicnacs__40__4018077798818");
            InitialBoxValues.Add("35", "malburner_partysticks__40__7610200279682");
            InitialBoxValues.Add("36", "None");
            InitialBoxValues.Add("37", "None");
            InitialBoxValues.Add("38", "None");
            InitialBoxValues.Add("39", "None");
            InitialBoxValues.Add("40", "bueno___43__4008400320328");
            InitialBoxValues.Add("41", "oreo___66__84100733");
            InitialBoxValues.Add("42", "snickers___50__5000159461122");
            InitialBoxValues.Add("43", "twix___50__5000159459228");
            InitialBoxValues.Add("44", "bifi_roll__50__4251097402635");
            InitialBoxValues.Add("45", "c+swiss_dosenabisicetea__33__9120025930135");
            InitialBoxValues.Add("46", "c+swiss_dosenabisicetea__33__9120025930135");
            InitialBoxValues.Add("47", "caprisun_multivitamin__20__4000177605004");
            InitialBoxValues.Add("48", "caprisun_multivitamin__20__4000177605004");
            InitialBoxValues.Add("49", "comella_schokodrink__33__7613100037253");
            InitialBoxValues.Add("50", "redbull___33__90162909");
            InitialBoxValues.Add("51", "redbull___33__90162909");
            InitialBoxValues.Add("52", "redbull___33__90162909");
            InitialBoxValues.Add("53", "redbull_light__33__90162800");
            InitialBoxValues.Add("54", "redbull___33__90162909");
            InitialBoxValues.Add("55", "coke__dose_33__54491472");
            InitialBoxValues.Add("56", "fuse_lemon_dose_33__5449000235947");
            InitialBoxValues.Add("57", "tiki_himbeer_brause__50__00000000009342");
            InitialBoxValues.Add("58", "caferoyal_classicmacchiato__33__7617014164487");
            InitialBoxValues.Add("59", "7days_croissantschoko_packung_80_1_0000000000003");
            InitialBoxValues.Add("60", "coke___50__54491472");
            InitialBoxValues.Add("61", "coke___50__54491472");
            InitialBoxValues.Add("62", "coke_zero_flasche_50__5449000131836");
            InitialBoxValues.Add("63", "fanta___50__40822938");
            InitialBoxValues.Add("64", "fuse_peach__50__5449000236623");
            InitialBoxValues.Add("65", "fuse_lemon__50__5449000235947");
            InitialBoxValues.Add("66", "ramseier_jusdepomme__50__7610057001078");
            InitialBoxValues.Add("67", "volvic_pinapple__50__305764335648");
            InitialBoxValues.Add("68", "valser_classic__50__76404160");
            InitialBoxValues.Add("69", "valser_still__50__7610335002575");
        }

        return InitialBoxValues;
    }
}
